version: '3.8'

services:
  server:
    build:
      context: ./serv
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./serv:/app
      - /app/node_modules
    command: ["node", "index.js"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
