services:
  server:
    build:
      context: ./serv
    working_dir: /app
    volumes:
      - ./serv:/app
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
    working_dir: /app
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"