services:
  server:
    image: node:18
    working_dir: /app
    volumes:
      - ./serv:/app
    command: sh -c "npm install && node index.js"
    ports:
      - "3000:3000"

  client:
    image: node:18
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"